name: Trigger Main Deploy

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  notify-main-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Main Repo Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: SeifEldin15/final-cloutware
          event-type: submodule-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "video-processing"}'
